#!/usr/bin/env bash
# A script that send a file to the remote server

# Accepts 4 parameter

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=0 -i "$4" "$1" "$3@$2":~/
fi
