#!/usr/bin/env bash
# Install nginx on your web-01 server & listening on port 80
# Allow nginx server on firewall

set -e
echo -e "Update and install nginx server. \n"
sudo apt-get -y -qq && sudo apt-get install nginx -y

echo -e "\nServer initializing\n"
# Satring Nginx service
sudo service nginx start

# Allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# User ownership to website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R 755 /var/www

# Backup
if [ -f /var/www/html/index.nginx-debian.html ]; then
	cp /var/www/html/index.ngix-debian.html /var/www/html/index.nginx-debian.html.bckp
fi

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart the server
sudo service nginx restart

echo -e "\nCompleted\n"
