#!/usr/bin/env bash
# Installing nginx on a remote server via ssh on your local machine

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
