#!/usr/bin/env bash
#Connecting to remote server without using password

Host *
    passwordAuthentication no
    identityFile ~/.ssh/school
    authorized_keys yes
    HostName 54.83.139.181
    user ubuntu
